services:
  - type: web
    name: node-postgres-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: core-postgres-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: core-postgres-db
    plan: free
