services:
  - type: web
    name: crevanotap-testing
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: PAYSTACK_CALLBACK_URL
        sync: false
